version: "3.9"
services:
  app:
    container_name: music-front
    image: music-front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    tty: true
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    working_dir: /workspace
    ports:
      - 8080:8080
      - 5173:5173
      - 3000:3000
