version: "3.9"
services:
  music-frontend:
    container_name: music-front
    image: music-front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    tty: true
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    working_dir: /workspace
    ports:
      - "8081:8081"
      - "5173:5173"

